import { StyleSheet } from "react-native";

export const CartSrceenStyles = StyleSheet.create({
  view222: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    marginHorizontal: 10,
    justifyContent: "space-between",
  },
  Texr32: { fontSize: 16, fontWeight: "500", width: 230 },
  Texr31: { fontSize: 16, fontWeight: "500" },
  contaoiner: { flex: 1 },
  Scro1: { marginTop: 10 },
  Scro2: { paddingBottom: 160 },
  texr30: { fontSize: 16, fontWeight: "bold" },
  View1: {
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  view2: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    marginHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  View3: {
    marginTop: 16,
    marginHorizontal: 15,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
  },
  View4: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  View5: {
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    borderColor: "#DEDEDE",
    borderWidth: 0.5,
    borderRadius: 5,
  },
  View6: { padding: 10 },
  view7: {
    alignItems: "center",
    justifyContent: "center",
  },
  View8: { marginHorizontal: 10 },
  View9: {
    backgroundColor: "#fff",
    borderRadius: 13,
    padding: 10,
    marginTop: 15,
  },
  View10: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  View11: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 8,
  },
  View12: {
    flexDirection: "row",
    alignItems: "center",
  },
  View13: { borderColor: "gray", height: 1, borderWidth: 0.5 },
  View14: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  view15: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  View16: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 8,
  },
  View17: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  view18: {
    padding: 16,
    backgroundColor: "#fff",
    flexDirection: "row",

    borderRadius: 8,
    flexDirection: "row", // Hiển thị ngang
  },
  Text1: { fontSize: 17, fontWeight: "600", marginLeft: 3 },
  Text2: { fontSize: 16, fontWeight: "500" },
  Texr3: { fontSize: 16, fontWeight: "700", color: "#ff4500" },
  Text4: { width: 100, fontSize: 16, fontWeight: "600" },
  Text5: {
    color: "green",
    fontSize: 20,
    paddingHorizontal: 6,
    fontWeight: "600",
  },
  Text6: { marginLeft: 20 },
  Text7: { fontSize: 16, fontWeight: "600" },
  Texxt8: { margin: 10, borderRadius: 10, padding: 10 },
  Text9: { fontSize: 16, fontWeight: "bold" },
  Text10: { fontSize: 18, fontWeight: "400", color: "gray" },
  Text11: { fontSize: 18, fontWeight: "400" },
  Texxt12: {
    fontSize: 18,
    fontWeight: "400",
    color: "#FF4500",
  },
  Text13: { fontSize: 18, fontWeight: "500", color: "gray" },
  Texxt14: {
    fontSize: 18,
    fontWeight: "400",
    color: "#FF4500",
    marginVertical: 10,
  },
  text15: {
    fontSize: 18,
    fontWeight: "400",
    color: "#FF4500",
    marginVertical: 10,
  },
  text16: { fontSize: 18, fontWeight: "bold" },
  text23: { fontSize: 16, fontWeight: "600", color: "#222", right: 15 },
  Text17: {
    fontSize: 18,
    fontWeight: "bold",
  },
  Text18: { textAlign: "center", fontSize: 16, fontWeight: "600" },
  Text19: { fontSize: 16, fontWeight: "600" },
  Text20: { fontSize: 17, color: "#00AB77" },
  Texxt21: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  text24: {
    fontSize: 14,
    color: "#666",
    width: 30,

    flexShrink: 1,
    textAlign: "left",
  },
  prove1: {
    margin: 10,
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#fff",
    flexShrink: 1,
  },
  prover2: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderTopWidth: 1,
    height: 130,
  },
  prover3: {
    backgroundColor: "#00AB77",
    padding: 10,
    width: 180,
    borderRadius: 8,
  },
});
