import { StyleSheet } from "react-native";

export const MenuScreenStyles = StyleSheet.create({
  container: {
    height: 300,
    backgroundColor: "#b0c4DE",
    borderBottomRightRadius: 40,
    borderBottomLeftRadius: 40,
  },
  View1: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    margin: 10,
  },
  View2: { flexDirection: "row", alignItems: "center" },
  Text1: { fontSize: 16, fontWeight: "600", marginLeft: 4 },
  View3: {
    backgroundColor: "#fff",
    height: 210,
    marginHorizontal: 20,
    marginVertical: 5,
    padding: 10,
    borderRadius: 15,
  },
  View4: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  Text2: { fontSize: 19, fontWeight: "bold" },
  View5: { flexDirection: "row", alignItems: "center" },
  View6: { flexDirection: "row", alignItems: "center", marginTop: 3 },
  View7: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  View8: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  View9: { flexDirection: "row", alignItems: "center", marginTop: 10 },

  prver: {
    width: 60,
    height: 60,
    borderRadius: 40,
    justifyContent: "center",
    backgroundColor: "#000",
    marginLeft: "auto",
    position: "absolute",
    right: 25,
    alignContent: "center",
    zIndex: 10,
  },

  prver2: {
    backgroundColor: "#00AB77",
    width: "90%",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    left: "5%",
    zIndex: 5,
    elevation: 4,
  },

  categoryModal: {
    width: 190,
    maxHeight: 250,
    backgroundColor: "#000",
    position: "absolute",
    right: 10,
    borderRadius: 7,
    padding: 10,
  },
  categoryItem: {
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },

  Text3: { marginLeft: 3, fontSize: 17, fontWeight: "400" },
  Text4: { marginLeft: 3, fontSize: 17, fontWeight: "400" },
  Text5: { marginTop: 8, color: "gray", fontSize: 17 },
  Text6: { marginLeft: 15, fontSize: 15, fontWeight: "bold" },
  Text7: { borderColor: "gray", borderWidth: 0.6, height: 1, marginTop: 12 },
  Text8: { marginLeft: 7, color: "gray", fontSize: 16 },
  Text9: {
    textAlign: "center",
    fontSize: 17,
    fontWeight: "500",
    marginTop: 10,
  },
  Text10: { borderColor: "gray", borderWidth: 0.6, height: 1, marginTop: 12 },
  Text11: { textAlign: "center", marginTop: 20 },
  Text12: { textAlign: "center", color: "#fff", fontWeight: "500" },
  Text13: { color: "#D0D0D0", fontWeight: "600", fontSize: 19 },
  Text14: { color: "#D0D0D0", textAlign: "center", marginTop: 20 },
  Text15: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  Text16: { color: "#fff", fontWeight: "500", fontSize: 14, marginTop: 3 },
  Text17: { color: "#fff", fontWeight: "600", fontSize: 16 },
});
